# Generated by Django 2.2 on 2022-12-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20221204_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
